"""initial_schema

Revision ID: fa1c4e2f6b5d
Revises: 
Create Date: 2026-03-01 16:37:55.825888

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa1c4e2f6b5d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('memory_type', sa.String(length=30), nullable=False),
    sa.Column('direction_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_event', sa.String(length=200), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_memory_memory_id'), 'market_memory', ['memory_id'], unique=True)
    op.create_index(op.f('ix_market_memory_symbol'), 'market_memory', ['symbol'], unique=False)
    op.create_index('ix_market_memory_symbol_type_valid', 'market_memory', ['symbol', 'memory_type', 'valid_until'], unique=False)
    op.create_index(op.f('ix_market_memory_valid_until'), 'market_memory', ['valid_until'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_pips', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_opened', 'trades', ['symbol', 'opened_at'], unique=False)
    op.create_index(op.f('ix_trades_ticket'), 'trades', ['ticket'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_ticket'), table_name='trades')
    op.drop_index('ix_trades_symbol_opened', table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_market_memory_valid_until'), table_name='market_memory')
    op.drop_index('ix_market_memory_symbol_type_valid', table_name='market_memory')
    op.drop_index(op.f('ix_market_memory_symbol'), table_name='market_memory')
    op.drop_index(op.f('ix_market_memory_memory_id'), table_name='market_memory')
    op.drop_table('market_memory')
    # ### end Alembic commands ###
