"""スキーマモジュール"""

from __future__ import annotations

from autotrader.web.schemas.requests import (
    AccountPresetRequest,
    ReloadLogicRequest,
    SettingsUpdateRequest,
    SwitchAccountRequest,
    TradingConfigUpdate,
)
from autotrader.web.schemas.responses import (
    AccountPresetResponse,
    AccountPresetsResponse,
    AnalysisResponse,
    ApiResponse,
    CandleResponse,
    CapitalManagementConfigResponse,
    DashboardResponse,
    EconomicEventResponse,
    EntryFilterConfigResponse,
    FundamentalCalendarResponse,
    FundamentalNewsResponse,
    HealthResponse,
    IndicatorResponse,
    IndicatorSeriesResponse,
    MT5StatusResponse,
    NewsItemResponse,
    PositionManagementConfigResponse,
    PositionResponse,
    ReloadLogicResponse,
    ReloadStatusResponse,
    SettingsResponse,
    SignalResponse,
    TradeResponse,
    TradeSummaryResponse,
    TradingConfigResponse,
    TradingModeResponse,
)

__all__ = [
    "ApiResponse",
    "HealthResponse",
    "DashboardResponse",
    "SignalResponse",
    "PositionResponse",
    "TradeResponse",
    "TradeSummaryResponse",
    "IndicatorResponse",
    "IndicatorSeriesResponse",
    "CandleResponse",
    "SettingsResponse",
    "SettingsUpdateRequest",
    "SwitchAccountRequest",
    "TradingConfigResponse",
    "TradingConfigUpdate",
    "EntryFilterConfigResponse",
    "CapitalManagementConfigResponse",
    "PositionManagementConfigResponse",
    "MT5StatusResponse",
    "TradingModeResponse",
    "AnalysisResponse",
    "AccountPresetResponse",
    "AccountPresetsResponse",
    "AccountPresetRequest",
    "NewsItemResponse",
    "EconomicEventResponse",
    "FundamentalNewsResponse",
    "FundamentalCalendarResponse",
    "ReloadLogicRequest",
    "ReloadLogicResponse",
    "ReloadStatusResponse",
]
